"""
Official Verified Registry of Statutory Civic Procedures in Karachi.
Anti-Hallucination Verified Source of Truth for Nigraan (§7 Phase 4).
"""

DEFAULT_FALLBACK_PROCEDURES = [
    {
        "id": "cnic-renewal",
        "name": "CNIC Renewal",
        "category": "Identity & Civil Status",
        "description": "Official standard and urgent renewal of Computerized National Identity Cards (CNIC) / Smart National Identity Cards (SNIC) for Pakistani citizens residing in Karachi.",
        "last_verified_at": "2026-01-15",
        "source_url": "https://www.nadra.gov.pk/identity/identity-cnic/",
        "required_documents": [
            {
                "id": "doc-cnic-1",
                "document_name": "Original Expired CNIC / SNIC",
                "notes": "Must be handed over for punching/cancellation upon collection of new card",
                "is_mandatory": True,
            },
            {
                "id": "doc-cnic-2",
                "document_name": "Photocopy of Parent or Spouse CNIC",
                "notes": "Used for computerized biometric cross-verification with NADRA database",
                "is_mandatory": True,
            },
            {
                "id": "doc-cnic-3",
                "document_name": "Proof of Address Update (Utility bill or Registered Tenancy / Lease Agreement)",
                "notes": "Only mandatory if your permanent or current residential address is being updated",
                "is_mandatory": False,
            },
            {
                "id": "doc-cnic-4",
                "document_name": "Marriage Certificate / Nikkahnama (for married females updating status)",
                "notes": "Mandatory if updating marital status from single to married",
                "is_mandatory": False,
            },
        ],
        "authorities": [
            {
                "id": "auth-cnic-1",
                "office_name": "NADRA Mega Center DHA Phase 4",
                "address": "Main Korangi Road, Phase 4, Defence Housing Authority, Karachi",
                "hours_text": "Open 24 Hours / 7 Days a week",
                "contact_info": "Helpline: 1777 (mobile) | +92-51-111-786-100",
                "lat": 24.8387,
                "lng": 67.0673,
            },
            {
                "id": "auth-cnic-2",
                "office_name": "NADRA Mega Center North Nazimabad",
                "address": "Block L, Near Sakhi Hassan Chowrangi, North Nazimabad, Karachi",
                "hours_text": "Open 24 Hours / 7 Days a week",
                "contact_info": "Helpline: 1777",
                "lat": 24.9452,
                "lng": 67.0544,
            },
            {
                "id": "auth-cnic-3",
                "office_name": "NADRA Mega Center Siemens Chowrangi",
                "address": "B-2, SITE Industrial Area, Near Siemens Chowrangi, Karachi",
                "hours_text": "Open 24 Hours / 7 Days a week",
                "contact_info": "Helpline: 1777",
                "lat": 24.8988,
                "lng": 66.9972,
            },
        ],
        "roadmap_steps": [
            {
                "id": "step-cnic-1",
                "step_order": 1,
                "description": "Token Issuance: Present original expired CNIC at reception desk and obtain an electronic queue token according to selected priority tier (Normal: Rs 750, Urgent: Rs 1500, Executive: Rs 2500).",
                "requires_witness": False,
                "estimated_duration": "10-15 mins",
            },
            {
                "id": "step-cnic-2",
                "step_order": 2,
                "description": "Biometric Acquisition: Proceed to biometric counter for live digital photograph capture, 10-fingerprint scanning, and dual iris scan.",
                "requires_witness": False,
                "estimated_duration": "10 mins",
            },
            {
                "id": "step-cnic-3",
                "step_order": 3,
                "description": "Data Verification & Review: Move to Registration Officer counter. Confirm all personal particulars (name, parental info, address). Any corrections must be submitted here.",
                "requires_witness": False,
                "estimated_duration": "15 mins",
            },
            {
                "id": "step-cnic-4",
                "step_order": 4,
                "description": "Draft Form Review: Receive printed identity draft summary. Scrutinize spellings and address details, affix signature or thumb impression.",
                "requires_witness": False,
                "estimated_duration": "5 mins",
            },
            {
                "id": "step-cnic-5",
                "step_order": 5,
                "description": "Tracking Voucher Issuance: Receive stamped payment and tracking receipt containing your unique 11-digit NADRA tracking code and estimated collection date.",
                "requires_witness": False,
                "estimated_duration": "2 mins",
            },
        ],
    },
    {
        "id": "sindh-domicile",
        "name": "Sindh Domicile & PRC Certificate",
        "category": "Citizenship & Residence",
        "description": "Statutory issuance of Permanent Resident Certificate (PRC Form P-1) and Domicile Certificate by the Government of Sindh District Administration for admissions, exams, and government employment.",
        "last_verified_at": "2026-02-01",
        "source_url": "https://commissionerkarachi.gos.pk/",
        "required_documents": [
            {
                "id": "doc-dom-1",
                "document_name": "Original CNIC / Form-B of Applicant + 2 Attested Copies",
                "notes": "Attested by Grade 17+ Government Gazette Officer",
                "is_mandatory": True,
            },
            {
                "id": "doc-dom-2",
                "document_name": "Father / Guardian CNIC + Sindh Domicile & PRC Copy",
                "notes": "Mandatory to substantiate domicile by descent",
                "is_mandatory": True,
            },
            {
                "id": "doc-dom-3",
                "document_name": "Five (5) Passport Size Photographs with White Background",
                "notes": "Two attested on front, two on reverse",
                "is_mandatory": True,
            },
            {
                "id": "doc-dom-4",
                "document_name": "Educational Certificates (Matriculation Certificate / Marks Sheet)",
                "notes": "Showing school attended in Karachi to establish uninterrupted physical residence",
                "is_mandatory": True,
            },
            {
                "id": "doc-dom-5",
                "document_name": "Recent Electricity or Sui Gas Utility Bill of Karachi Residence",
                "notes": "Bill from last 3 months bearing the residential address claimed in application",
                "is_mandatory": True,
            },
            {
                "id": "doc-dom-6",
                "document_name": "Attested Stamp Paper Affidavit (Rs. 100/50)",
                "notes": "Declaring applicant does not possess domicile of any other district/province, signed before Oath Commissioner",
                "is_mandatory": True,
            },
        ],
        "authorities": [
            {
                "id": "auth-dom-1",
                "office_name": "Deputy Commissioner (DC) Office South",
                "address": "4th Floor, Sindh Secretariat Building No. 2, Kamal Ataturk Road, Karachi",
                "hours_text": "Monday - Friday, 09:00 AM - 04:00 PM",
                "contact_info": "Phone: +92-21-99208000 | Email: dc.south@sindh.gov.pk",
                "lat": 24.8569,
                "lng": 67.0182,
            },
            {
                "id": "auth-dom-2",
                "office_name": "Deputy Commissioner (DC) Office Korangi",
                "address": "Sector 31-D, Near Bilal Chowrangi, Korangi Industrial Area, Karachi",
                "hours_text": "Monday - Friday, 09:00 AM - 04:00 PM",
                "contact_info": "Phone: +92-21-99333900 | Email: dc.korangi@sindh.gov.pk",
                "lat": 24.8415,
                "lng": 67.1350,
            },
            {
                "id": "auth-dom-3",
                "office_name": "Deputy Commissioner (DC) Office East",
                "address": "Block 14, Gulshan-e-Iqbal, Near Civic Center, Karachi",
                "hours_text": "Monday - Friday, 09:00 AM - 04:00 PM",
                "contact_info": "Phone: +92-21-99230555",
                "lat": 24.9080,
                "lng": 67.0750,
            },
        ],
        "roadmap_steps": [
            {
                "id": "step-dom-1",
                "step_order": 1,
                "description": "Affidavit Attestation & File Preparation: Purchase official Domicile file docket and print statutory affidavit on Rs. 100 legal stamp paper. Sign in presence of Oath Commissioner.",
                "requires_witness": False,
                "estimated_duration": "30-45 mins",
            },
            {
                "id": "step-dom-2",
                "step_order": 2,
                "description": "Assistant Commissioner (AC) Endorsement: Visit the Assistant Commissioner sub-division office corresponding to your residence for preliminary document verification and signature on Form P-1.",
                "requires_witness": False,
                "estimated_duration": "1-2 business days",
            },
            {
                "id": "step-dom-3",
                "step_order": 3,
                "description": "DC Citizen Facilitation Counter Submission: Submit verified file with fee payment challan (National Bank of Pakistan official fee Rs 200) at Deputy Commissioner Citizen Service Window. Biometric and webcam snapshot registered.",
                "requires_witness": False,
                "estimated_duration": "30 mins",
            },
            {
                "id": "step-dom-4",
                "step_order": 4,
                "description": "Police Verification & Approval: Administrative background check and DC final seal signature.",
                "requires_witness": False,
                "estimated_duration": "3-5 business days",
            },
            {
                "id": "step-dom-5",
                "step_order": 5,
                "description": "Collection: Collect original sealed green Domicile Certificate and PRC Form P-1 upon presenting stamped submission voucher.",
                "requires_witness": False,
                "estimated_duration": "5 mins",
            },
        ],
    },
    {
        "id": "driving-license",
        "name": "Driving License Renewal (Sindh Police)",
        "category": "Transport & Licensing",
        "description": "Official statutory renewal process for non-commercial (Motorcycle / Motorcar M/Car) computerized driving licenses issued by the Sindh Police Driving License Branch.",
        "last_verified_at": "2026-02-10",
        "source_url": "https://dls.sindhpolice.gov.pk/",
        "required_documents": [
            {
                "id": "doc-lic-1",
                "document_name": "Original Expired Driving License",
                "notes": "Must be surrendered or physically inspected by licensing authority",
                "is_mandatory": True,
            },
            {
                "id": "doc-lic-2",
                "document_name": "Valid Original CNIC + 2 Attested Photocopies",
                "notes": "Must show Karachi residential address or Sindh address",
                "is_mandatory": True,
            },
            {
                "id": "doc-lic-3",
                "document_name": "Medical Fitness Certificate (Form B)",
                "notes": "Mandatory for drivers aged 50+ or commercial endorsement; issued by on-site Sindh Police medical doctor",
                "is_mandatory": True,
            },
            {
                "id": "doc-lic-4",
                "document_name": "Three (3) Passport Size Photographs",
                "notes": "Passport size with light blue or white background",
                "is_mandatory": True,
            },
        ],
        "authorities": [
            {
                "id": "auth-lic-1",
                "office_name": "Driving License Branch Clifton",
                "address": "Khayaban-e-Roomi, Block 8, Clifton, Near Teen Talwar, Karachi",
                "hours_text": "Monday - Saturday: 08:30 AM - 05:00 PM (Night shift until 11:00 PM)",
                "contact_info": "Helpline: +92-21-99250522 | Web: dls.sindhpolice.gov.pk",
                "lat": 24.8290,
                "lng": 67.0345,
            },
            {
                "id": "auth-lic-2",
                "office_name": "Driving License Branch Nazimabad",
                "address": "Near Nazimabad Petrol Pump, Block 7, Nazimabad, Karachi",
                "hours_text": "Monday - Saturday: 08:30 AM - 04:30 PM",
                "contact_info": "Phone: +92-21-99260555",
                "lat": 24.9125,
                "lng": 67.0310,
            },
            {
                "id": "auth-lic-3",
                "office_name": "Driving License Branch Korangi",
                "address": "Sector 15, Near Brookes Chowrangi, Korangi Industrial Area, Karachi",
                "hours_text": "Monday - Saturday: 09:00 AM - 04:00 PM",
                "contact_info": "Phone: +92-21-35050511",
                "lat": 24.8320,
                "lng": 67.1215,
            },
        ],
        "roadmap_steps": [
            {
                "id": "step-lic-1",
                "step_order": 1,
                "description": "Entry & Medical Inspection: Check in at reception, present expired license and CNIC. Undergo quick on-site visual acuity eye-test with medical officer.",
                "requires_witness": False,
                "estimated_duration": "15 mins",
            },
            {
                "id": "step-lic-2",
                "step_order": 2,
                "description": "Fee Deposit: Deposit official government renewal fee at on-site National Bank of Pakistan (NBP) counter (3-year or 5-year renewal fee schedule).",
                "requires_witness": False,
                "estimated_duration": "10 mins",
            },
            {
                "id": "step-lic-3",
                "step_order": 3,
                "description": "Data Verification & Biometrics: Counter officer verifies CNIC credentials, captures live digital photo and electronic thumbprint.",
                "requires_witness": False,
                "estimated_duration": "10 mins",
            },
            {
                "id": "step-lic-4",
                "step_order": 4,
                "description": "Temporary Permit & Dispatch: Receive printed provisional stamped renewal permit valid for 30 days while your physical smart card is printed and dispatched via Pakistan Post EMS.",
                "requires_witness": False,
                "estimated_duration": "5 mins",
            },
        ],
    },
]
